In [ ]:
pip install cdlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 228 kB 5.2 MB/s 
     |████████████████████████████████| 2.6 MB 45.7 MB/s 
     |████████████████████████████████| 14.2 MB 6.9 MB/s 
     |████████████████████████████████| 50 kB 4.7 MB/s 
     |████████████████████████████████| 3.1 MB 42.1 MB/s 
  Created wheel for pyclustering: filename=pyclustering-0.10.1.2-py3-none-any.whl size=2395122 sha256=20b151bd3fb4cfb489f4ed1a11c946a407a5644ad2cf4f38636ab18b0b1671db
  Stored in directory: /root/.cache/pip/wheels/ea/87/6b/1e0568b5ba9dc6518a25338bae90bd8392f35206bb90bb10f1
  Created wheel for python-igraph: filename=python_igraph-0.9.11-py3-none-any.whl size=9074 sha256=4396e495bf012e60e4eb52f679ffedce4e36bfd9ab99dc622caec715e46a3db7
  Stored in directory: /root/.cache/pip/wheels/7d/e4/0c/0c83f70bd0b99ce8aea47a21f8e52502169e7dd17808d12f30
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0

In [ ]:
pip install node2vec

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for node2vec: filename=node2vec-0.4.3-py3-none-any.whl size=5980 sha256=0a8168f56b600d1a79419c0fab0133b39bfe88f8894b1402e20593b76052922a
  Stored in directory: /root/.cache/pip/wheels/07/62/78/5202cb8c03cbf1593b48a8a442fca8ceec2a8c80e22318bae9
Successfully built node2vec


In [ ]:
pip install pulearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import networkx as nx
import csv
from sys import stdin
from networkx.algorithms.community import greedy_modularity_communities
from networkx.algorithms.community import k_clique_communities
from networkx.algorithms.community import asyn_lpa_communities
from networkx.algorithms.community import modularity
from cdlib import algorithms, readwrite, viz
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import accuracy_score
from gensim.models import Word2Vec
#import markov_clustering as mc
#import igraph
#conda install -c conda-forge python-levenshtein
#from cdlib import algorithms
#import cairocffi
#import igraph

Note: to be able to use all crisp methods, you need to install some additional packages:  {'infomap', 'leidenalg', 'wurlitzer', 'karateclub', 'graph_tool'}
Note: to be able to use all overlapping methods, you need to install some additional packages:  {'karateclub', 'ASLPAw'}
Note: to be able to use all bipartite methods, you need to install some additional packages:  {'wurlitzer', 'infomap', 'leidenalg'}


In [ ]:
filename = "pnas.2025581118.sd02.csv"
data = pd.read_csv(filename)
Graphtype = nx.Graph()
G = nx.from_pandas_edgelist(data, 
                            source="proteinA_entrezid",
                            target="proteinB_entrezid",
                            edge_attr='databases', create_using=Graphtype)

G.remove_edges_from(list(nx.selfloop_edges(G)))
G2 = nx.to_undirected(G)


Gcc = sorted(nx.connected_components(G2), key=len, reverse=True)

G0 = G.subgraph(Gcc[0]) #Hay 18446 nodos en G0

FileNotFoundError: ignored

In [ ]:

data = pd.read_excel('Copia_de_Criterios.xlsx', sheet_name= "Criterios")
data

initial_alias converted_alias  Canonical  GIM  Colorrectal  Candidatos  \
0               9796          PHYHIP      0.000  0.0          0.0       0.000   
1               7918          GPANK1      0.000  0.0          0.0       0.000   
2               8233           ZRSR2      0.125  0.0          0.0       0.000   
3               4899            NRF1      0.000  0.0          0.0       0.000   
4               5297           PI4KA      0.000  0.0          0.0       0.125   
...              ...             ...        ...  ...          ...         ...   
18546          26254            OPTC      0.000  0.0          0.0       0.000   
18547         348158          ACSM2B      0.000  0.0          0.0       0.000   
18548         221391            OPN5      0.000  0.0          0.0       0.000   
18549          50651         SLC45A1      0.000  0.0          0.0       0.000   
18550         201625          DNAH12      0.000  0.0          0.0       0.125   

       Hallmarks  Driver_genes  Unnamed: 8  Ponderado  Unnamed: 10  \
0          0.125           0.0         NaN      0.125          NaN   
1          0.000           0.0         NaN      0.000          NaN   
2          0.000           0.0         NaN      0.125          NaN   
3          0.000           0.0         NaN      0.000          NaN   
4          0.125           0.0         NaN      0.250          NaN   
...          ...           ...         ...        ...          ...   
18546      0.000           0.0         NaN      0.000          NaN   
18547      0.000           0.0         NaN      0.000          NaN   
18548      0.000           0.0         NaN      0.000          NaN   
18549      0.000           0.0         NaN      0.000          NaN   
18550      0.000           0.0         NaN      0.125          NaN   

       Unnamed: 11  Unnamed: 12 Unnamed: 13 Unnamed: 14  Unnamed: 15  \
0              NaN          NaN   Canonical         GIM  Colorrectal   
1              NaN          NaN           0           0            0   
2              NaN          NaN       17960       18112        18466   
3              NaN          NaN         NaN         NaN          NaN   
4              NaN          NaN         NaN         NaN          NaN   
...            ...          ...         ...         ...          ...   
18546          NaN          NaN         NaN         NaN          NaN   
18547          NaN          NaN         NaN         NaN          NaN   
18548          NaN          NaN         NaN         NaN          NaN   
18549          NaN          NaN         NaN         NaN          NaN   
18550          NaN          NaN         NaN         NaN          NaN   

      Unnamed: 16 Unnamed: 17  
0      Candidatos   Hallmarks  
1               0           0  
2           15938       13336  
3             NaN         NaN  
4             NaN         NaN  
...           ...         ...  
18546         NaN         NaN  
18547         NaN         NaN  
18548         NaN         NaN  
18549         NaN         NaN  
18550         NaN         NaN  

[18551 rows x 18 columns]

In [ ]:
a = []
b = []

for index, row in data.iterrows():
  a.append(row['initial_alias'])
  b.append(row['Ponderado'])


In [ ]:

for node in range(len(a)): #----------Asignar valores ponderados a los nodos
	if a[node] in G0:
		G0.nodes[a[node]]["pond"] = b[node]


for edge in G0.edges: #---------------Asignacion de los pesos de las conexiones a los ejes 
	G0[edge[0]][edge[1]]["weight"] = (G.nodes[edge[0]]["pond"]) + (G.nodes[edge[1]]["pond"])


In [ ]:

#Se borran los nodos con ponderado 0

G0_unfrozen= nx.Graph(G0)
array_edges_0 = []
for edge in G0_unfrozen.edges:
	if G0_unfrozen[edge[0]][edge[1]]["weight"] == 0:
		array_edges_0.append((edge[0], edge[1]))

G0_unfrozen.remove_edges_from(array_edges_0)
isolates = nx.isolates(G0_unfrozen)
isolates = list(isolates)
print()
print("antes",len(G0_unfrozen.nodes))
print("nodos lista isolates",len(isolates))
G0_unfrozen.remove_nodes_from(isolates)

print("después",len(G0_unfrozen.nodes))
print(len(G0_unfrozen.edges), len(G0.edges), len(G0.edges)-len(G0_unfrozen.edges))



antes 18446
nodos lista isolates 662
después 17784
255693 322159 66466


# Algoritmo de detección de comunidades


Algoritmos no-sobrelapantes

In [ ]:

"""
asyn_lpa_communities


third_communities = nx.algorithms.community.asyn_lpa_communities(G0_unfrozen, "weight")

for idx, com in enumerate(third_communities):
    dic[str(idx)] = list(com)
"""

"""
Greedy modularity communities



four_communities = nx.algorithms.community.greedy_modularity_communities(G0_unfrozen, "weight")
for idx, com in enumerate(four_communities):
    dic[str(idx)] = list(com)
"""

'\nGreedy modularity communities\n\n\n\nfour_communities = nx.algorithms.community.greedy_modularity_communities(G0_unfrozen, "weight")\nfor idx, com in enumerate(four_communities):\n    dic[str(idx)] = list(com)\n'

Algoritmos sobrelapantes

In [ ]:
"""

first_overlapping_communities = algorithms.angel(G0_unfrozen, min_community_size= 3, threshold= 0.7)

readwrite.write_community_csv(first_overlapping_communities,"angel_algorithm.csv", ",")

"""


"""

second_overlapping_communities = algorithms.ipca(G0_unfrozen, weights= "weight", t_in= 0.7)
readwrite.write_community_csv(second_overlapping_communities,"v2_ipca_algorithm.csv")

"""




'\n\nsecond_overlapping_communities = algorithms.ipca(G0_unfrozen, weights= "weight", t_in= 0.7)\nreadwrite.write_community_csv(second_overlapping_communities,"v2_ipca_algorithm.csv")\n\n'

#Machine Learning

In [ ]:
import gensim
model = gensim.models.KeyedVectors.load_word2vec_format('resultado_pecanpy.emb')

In [ ]:
node_embeddings = (model.wv.vectors)

In [ ]:
train_csv = "train.csv"
train_data = pd.read_csv(train_csv)
train_data

Id  Driver_genes  Colorrectal  Suma  Target
0           7316          0.00         0.00  0.00       0
1           2624          0.00         0.25  0.25       1
2           2033          0.25         0.00  0.25       1
3          10664          0.25         0.00  0.25       1
4           7157          0.25         0.25  0.50       1
...          ...           ...          ...   ...     ...
17779     139221          0.00         0.00  0.00       0
17780      57636          0.00         0.00  0.00       0
17781     286749          0.00         0.00  0.00       0
17782  105375355          0.00         0.00  0.00       0
17783  111240474          0.00         0.00  0.00       0

[17784 rows x 5 columns]

In [ ]:
train_data['Target'] = train_data['Target'].astype('int') 

In [ ]:
# X will hold the 128-dimensional input features
X = node_embeddings
# y holds the corresponding target values
y = train_data['Target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.3, test_size=None)

In [ ]:
clf = LogisticRegressionCV(
    Cs=10, cv=10, scoring="accuracy", verbose=False, multi_class="ovr", max_iter=300
)
clf.fit(X_train, y_train)

LogisticRegressionCV(cv=10, max_iter=300, multi_class='ovr', scoring='accuracy',
                     verbose=False)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.9710430137756536

#Se procede a hacer SMOTE para equilibrar dataset

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter
counter = Counter(y_train)
print('Antes', counter)

smt = SMOTE()

X_train_sm, y_train_sm = smt.fit_resample(X_train, y_train)

counter = Counter(y_train_sm)
print('Después', counter)

NameError: ignored

#Regresión Logistíca

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0,max_iter=500).fit(X_train_sm,y_train_sm)
Lprediction = model.predict(X_test)
model.score(X_test, y_test)

0.8192999718864211

In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
Confusion_matrix = confusion_matrix(Lprediction, y_test)
Confusion_matrix

array([[11509,   264],
       [ 2307,   148]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,Lprediction))

              precision    recall  f1-score   support

           0       0.98      0.83      0.90     13816
           1       0.06      0.36      0.10       412

    accuracy                           0.82     14228
   macro avg       0.52      0.60      0.50     14228
weighted avg       0.95      0.82      0.88     14228



#k-vecinos más cercanos

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
arr_pred = []
maxim_score = -1
KpredictionSelected = None 
for i in range(3,19):
  knc = KNeighborsClassifier(n_neighbors=i)
  knc.fit(X_train_sm, y_train_sm)
  Kprediction = knc.predict(X_test)
  score = knc.score(X_test, y_test)
  arr_pred.append(knc.score(X_test, y_test))
  if score > maxim_score:
    maxim_score = score
    KpredictionSelected = Kprediction
    
 
print("la mejor predicción es: ", maxim_score)
print("con el mejor n_neighbor siendo", arr_pred.index(maxim_score) +  3)


la mejor predicción es:  0.8888107956142817
con el mejor n_neighbor siendo 4


In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Confusion_matrix = confusion_matrix(KpredictionSelected, y_test)
Confusion_matrix

array([[12593,   359],
       [ 1223,    53]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,KpredictionSelected))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94     13816
           1       0.04      0.13      0.06       412

    accuracy                           0.89     14228
   macro avg       0.51      0.52      0.50     14228
weighted avg       0.95      0.89      0.92     14228



#Análisis discriminante lineal

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train_sm, y_train_sm)
ldaPrediction = lda.predict(X_test)
lda.score(X_test, y_test)

0.7854933933089683

In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Confusion_matrix = confusion_matrix(ldaPrediction, y_test)
Confusion_matrix

array([[11014,   250],
       [ 2802,   162]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,ldaPrediction))

              precision    recall  f1-score   support

           0       0.98      0.80      0.88     13816
           1       0.05      0.39      0.10       412

    accuracy                           0.79     14228
   macro avg       0.52      0.60      0.49     14228
weighted avg       0.95      0.79      0.86     14228



#Análisis discriminante cuadrático

In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train_sm, y_train_sm)
qdaPrediction = qda.predict(X_test)
qda.score(X_test, y_test)

0.9710430137756536

In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Confusion_matrix = confusion_matrix(qdaPrediction, y_test)
Confusion_matrix

array([[13816,   412],
       [    0,     0]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,qdaPrediction))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99     13816
           1       0.00      0.00      0.00       412

    accuracy                           0.97     14228
   macro avg       0.49      0.50      0.49     14228
weighted avg       0.94      0.97      0.96     14228



#Random Forest

In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier


clf=RandomForestClassifier(n_estimators=1000, bootstrap= 1000)
clf.fit(X_train_sm,y_train_sm)

y_pred=clf.predict(X_test)
clf.score(X_test, y_test)

0.9698481866741636

In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Confusion_matrix = confusion_matrix(y_pred, y_test)
Confusion_matrix

array([[13797,   410],
       [   19,     2]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98     13816
           1       0.10      0.00      0.01       412

    accuracy                           0.97     14228
   macro avg       0.53      0.50      0.50     14228
weighted avg       0.95      0.97      0.96     14228



#Se implementa pulearn

In [ ]:
    from pulearn import BaggingPuClassifier
    from sklearn.svm import SVC
    svc = SVC(C=10, kernel='rbf', gamma=0.4, probability=True)
    pu_estimator = BaggingPuClassifier(
        base_estimator=svc, n_estimators=15)
    pu_estimator.fit(X_train, y_train)

    y_pred = pu_estimator.predict(X_test)
    pu_estimator.score(X_test, y_test)

0.9706915940399213

In [ ]:
#Metricas de la Matriz de confusión
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
Confusion_matrix = confusion_matrix(y_pred, y_test)
Confusion_matrix

array([[13809,   410],
       [    7,     2]])

In [ ]:
#Calculo de las metricas Precision, Recall, F1-score 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99     13816
           1       0.22      0.00      0.01       412

    accuracy                           0.97     14228
   macro avg       0.60      0.50      0.50     14228
weighted avg       0.95      0.97      0.96     14228

